Modificacion nombres

diff --git a/workflows/main.yml b/workflows/main.yml
--- a/workflows/main.yml
+++ b/workflows/main.yml
@@ -24,19 +24,19 @@ jobs:
         run: |
           set -e
 
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/back-Ventas_SpringBoot:latest ./msv-ventas
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/back-Despachos_SpringBoot:latest ./msv-despacho
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tienda_Despachos:latest ./bd-videojuegos/inventario
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tienda_Ventas:latest ./bd-videojuegos/ventas
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/back-ventas_springboot:latest ./backend-ventas_springboot
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/back-despachos_springboot:latest ./backend-despachos_springboot
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tienda_despachos:latest ./BD/BD-Despachos
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tienda_ventas:latest ./BD/BD-Ventas
 
       - name: Push Docker images
         run: |
           set -e
 
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/back-Ventas_SpringBoot:latest
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/back-Despachos_SpringBoot:latest
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/db-inventario-videojuegos:latest
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tienda_Ventas:latest
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/back-ventas_springboot:latest
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/back-despachos_springboot:latest
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tienda_despachos:latest
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tienda_ventas:latest
 
       - name: Set up AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -120,10 +120,10 @@ jobs:
             docker-compose ps
 
             echo "Validando contenedores activos..."
-            docker ps --format '{{.Names}}' | grep -q "back-Despachos_SpringBoot" || { echo "ERROR: back-Despachos_SpringBoot no está activo"; exit 1; }
-            docker ps --format '{{.Names}}' | grep -q "back-Ventas_SpringBoot" || { echo "ERROR: back-Ventas_SpringBoot no está activo"; exit 1; }
+            docker ps --format '{{.Names}}' | grep -q "back-despachos_springboot" || { echo "ERROR: back-Despachos_SpringBoot no está activo"; exit 1; }
+            docker ps --format '{{.Names}}' | grep -q "back-ventas_springboot" || { echo "ERROR: back-Ventas_SpringBoot no está activo"; exit 1; }
             docker ps --format '{{.Names}}' | grep -q "backend_ventas" || { echo "ERROR: backend_ventas no está activo"; exit 1; }
-            docker ps --format '{{.Names}}' | grep -q "backennd_despachos" || { echo "ERROR: backennd_despachos no está activo"; exit 1; }
+            docker ps --format '{{.Names}}' | grep -q "backend_despachos" || { echo "ERROR: backennd_despachos no está activo"; exit 1; }
 
             echo "Validando endpoints internos..."
             if ! command -v curl >/dev/null 2>&1; then
